# Generated by Django 4.2.4 on 2024-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "custom user",
                "verbose_name_plural": "custom users",
            },
        ),
    ]
