# Generated by Django 4.2.4 on 2024-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, unique=True, verbose_name="Email"
            ),
        ),
    ]
