# Generated by Django 4.2.4 on 2024-09-24 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0011_alter_deal_image_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="invoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("NOT_PAID", "Not Paid"),
                            ("PAID", "Paid"),
                            ("PENDING_PAY", "Pending Payment"),
                            ("REJECTED", "Rejected"),
                            ("FRAUD", "Fraud"),
                            ("TIMEOUT", "Timeout"),
                            ("PENDING_CHECK", "Pending Check"),
                        ],
                        default="Pending Payment",
                        max_length=300,
                    ),
                ),
                ("total_price", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "gmail",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "al_phone_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Phone Number"
                    ),
                ),
                ("country", models.CharField(default="bangladesh", max_length=100)),
                ("division", models.CharField(blank=True, max_length=60)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=60)),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "payment_method",
                    models.CharField(default="cash_on_delivery", max_length=500),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "processing"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction", models.CharField(blank=True, max_length=500)),
                (
                    "transaction_image",
                    models.ImageField(blank=True, upload_to="media/transac/"),
                ),
                (
                    "invoice_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payment.invoice",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payment.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_note_admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=3000)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payment.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_quantity", models.IntegerField()),
                ("order_price", models.IntegerField()),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payment.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payment.order",
            ),
        ),
    ]
