# Generated by Django 4.2.4 on 2024-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="gmail",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
    ]
