# Generated by Django 4.2.4 on 2024-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("PROCESSING", "processing"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
