# Generated by Django 4.2.4 on 2024-09-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 27, 16, 13, 0, 167213, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
