# Generated by Django 4.2.4 on 2024-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_payment_date_created_payment_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_status",
            field=models.CharField(
                choices=[
                    ("NOT_PAID", "Not Paid"),
                    ("PAID", "Paid"),
                    ("PENDING_PAY", "Pending Payment"),
                    ("REJECTED", "Rejected"),
                    ("FRAUD", "Fraud"),
                    ("TIMEOUT", "Timeout"),
                    ("PENDING_CHECK", "Pending Check"),
                ],
                default="PENDING_PAY",
                max_length=300,
            ),
        ),
    ]
