# Generated by Django 4.2.4 on 2024-09-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_alter_invoice_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.order",
            ),
        ),
    ]
