# Generated by Django 4.2.4 on 2024-10-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_alter_payment_invoice_id_alter_payment_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="shipping_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
