# Generated by Django 4.2.4 on 2024-10-05 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0010_areashippingcost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areashippingcost",
            old_name="name",
            new_name="area_name",
        ),
        migrations.RenameField(
            model_name="areashippingcost",
            old_name="price",
            new_name="shipping_cost",
        ),
        migrations.AddField(
            model_name="areashippingcost",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="areashippingcost",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
