# Generated by Django 4.2.4 on 2024-10-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_categorytree_image"),
        ("payment", "0011_rename_name_areashippingcost_area_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_list",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
