# Generated by Django 4.2.4 on 2024-10-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0012_alter_order_list_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_image",
            field=models.ImageField(blank=True, upload_to="transac/"),
        ),
    ]
