# Generated by Django 4.2.4 on 2024-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_page_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "company",
                "verbose_name_plural": "company",
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["key"],
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
        ),
    ]
