# Generated by Django 4.2.4 on 2024-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_company_options_alter_page_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(upload_to="", verbose_name="/media/company/"),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="/media/company/"),
        ),
    ]
