# Generated by Django 4.2.4 on 2024-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_company_logo_alter_page_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(upload_to="media/ecom"),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(upload_to="media/ecom_product"),
        ),
    ]
