# Generated by Django 4.2.4 on 2024-10-07 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_company_logo_alter_page_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=40)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(blank=True, max_length=1000)),
                (
                    "contact_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Read", "Read"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=40,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=100)),
                ("Note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.IntegerField()),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "faq_status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default=False,
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="facebook",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="company",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
