# Generated by Django 4.2.4 on 2024-10-13 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_contactmessage_faq_company_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="facebook_url",
            field=models.URLField(
                default=django.utils.timezone.now, verbose_name="Facebook"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="whatsapp_url",
            field=models.URLField(
                default=django.utils.timezone.now, verbose_name="Whatsapp"
            ),
            preserve_default=False,
        ),
    ]
