# Generated by Django 4.2.4 on 2024-10-15 14:42

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_company_facebook_url_company_whatsapp_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
