# Generated by Django 4.2.4 on 2024-10-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_company_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(upload_to="ecom"),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(upload_to="ecom_product"),
        ),
    ]
