# Generated by Django 4.2.4 on 2024-12-05 17:06

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_siteicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteicon",
            name="mobile_bar_icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="icons/",
                validators=[home.models.validate_svg_file],
            ),
        ),
    ]
