# Generated by Django 4.2.4 on 2024-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["user"],
                "verbose_name": "cart",
                "verbose_name_plural": "cart",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["cart"],
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["user"],
                "verbose_name": "wishlist",
                "verbose_name_plural": "wishlist",
            },
        ),
    ]
