# Generated by Django 4.2.4 on 2024-09-27 18:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 27, 18, 38, 21, 437090, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlist",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
