# Generated by Django 4.2.4 on 2024-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_deal_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["title"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
