# Generated by Django 4.2.4 on 2024-10-09 14:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_deal_image_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("keywords", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="category/")),
                ("details", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")], max_length=20
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.categorytree",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
