# Generated by Django 4.2.4 on 2024-10-15 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_categorytree"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summery_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="categorytree",
            name="details",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=django.utils.timezone.now, verbose_name="Text"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.categorytree",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=django.utils.timezone.now, verbose_name="Text"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default=django.utils.timezone.now, verbose_name="Text"
            ),
            preserve_default=False,
        ),
    ]
