# Generated by Django 4.2.4 on 2024-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_product_summery_pdf_alter_categorytree_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summery_pdf",
            field=models.FileField(blank=True, null=True, upload_to="media/pdfs/"),
        ),
    ]
