# Generated by Django 4.2.4 on 2024-10-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_product_summery_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytree",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/category/"),
        ),
    ]
