# Generated by Django 4.2.4 on 2024-10-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytree",
            name="image",
            field=models.ImageField(blank=True, upload_to="category/"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="image",
            field=models.ImageField(upload_to="ecom_deal"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="ecom_product/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="summery_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
