# Generated by Django 4.2.4 on 2024-10-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="ads/")),
                ("link", models.URLField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["-start_date"],
            },
        ),
    ]
