# Generated by Django 4.2.4 on 2024-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_deal_section_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="section_setup",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hero", "Hero"),
                    ("Middle", "Middle"),
                    ("SubMiddle", "SubMiddle"),
                    ("Footer", "Footer"),
                ],
                default="Hero",
                max_length=255,
                verbose_name="Section Setup",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="section_setup",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hero", "Hero"),
                    ("Middle", "Middle"),
                    ("SubMiddle", "SubMiddle"),
                    ("Footer", "Footer"),
                ],
                default="Hero",
                max_length=255,
                verbose_name="Section Setup",
            ),
        ),
    ]
