# Generated by Django 4.2.4 on 2024-10-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_advertisement_section_setup_alter_deal_section_setup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="section_setup",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hero", "Hero"),
                    ("Middle", "Middle"),
                    ("SubMiddle", "SubMiddle"),
                    ("Footer", "Footer"),
                ],
                default="Hero",
                max_length=255,
                verbose_name="Adverticement Section Setup",
            ),
        ),
    ]
