# Generated by Django 4.2.4 on 2024-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_alter_advertisement_section_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="brands"),
        ),
        migrations.AddField(
            model_name="brand",
            name="showcase_section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anywhere", "Anywhere"),
                    ("Middle", "Middle"),
                    ("SubMiddle", "SubMiddle"),
                    ("Footer", "Footer"),
                ],
                default="Anywhere",
                max_length=255,
                verbose_name="Brand Showcase Section",
            ),
        ),
    ]
