# Generated by Django 4.2.4 on 2024-10-20 06:02

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_brand_created_at_brand_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="section_setup",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hero", "Hero"),
                    ("Middle", "Middle"),
                    ("SubMiddle", "SubMiddle"),
                    ("Footer", "Footer"),
                ],
                default="Hero",
                max_length=255,
                verbose_name="Advertisement Section Setup",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="show_hide",
            field=models.BooleanField(default=True, verbose_name="Show"),
        ),
        migrations.CreateModel(
            name="Variants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="product_variant/")),
                ("quantity", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.size",
                    ),
                ),
            ],
            bases=(models.Model, products.models.ImageTagMixin),
        ),
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="author/")),
                ("bio", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text")),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.genre",
                    ),
                ),
            ],
            bases=(models.Model, products.models.ImageTagMixin),
        ),
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.bookauthor",
                verbose_name="BookAuthor",
            ),
        ),
    ]
