# Generated by Django 4.2.4 on 2024-10-20 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0027_color_genre_size_alter_advertisement_section_setup_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variants",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variants",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
