# Generated by Django 4.2.4 on 2024-10-20 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_variants_created_at_variants_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookauthor",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=255, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
    ]
