# Generated by Django 4.2.4 on 2024-10-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.publication",
                verbose_name="Publication",
            ),
        ),
    ]
