# Generated by Django 4.2.4 on 2024-10-23 18:30

from django.db import migrations
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_product_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="address",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default=django.utils.timezone.now, verbose_name="Text"
            ),
            preserve_default=False,
        ),
    ]
