# Generated by Django 4.2.4 on 2024-10-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0032_alter_publication_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Discount Percentage",
            ),
        ),
    ]
