# Generated by Django 4.2.4 on 2024-10-26 18:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0034_category_created_at_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="category/",
                validators=[products.models.validate_svg_file],
            ),
        ),
    ]
