# Generated by Django 4.2.4 on 2024-10-26 19:26

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0035_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="featured",
        ),
        migrations.AddField(
            model_name="product",
            name="book_page",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="edition",
            field=models.CharField(blank=True, max_length=100, verbose_name="Edition"),
        ),
        migrations.AddField(
            model_name="product",
            name="isbn_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="ISBN"),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_keyword",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Text"
            ),
        ),
    ]
