# Generated by Django 4.2.4 on 2024-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_remove_product_featured_product_book_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=True, verbose_name="Show/Hide"),
        ),
    ]
