# Generated by Django 4.2.4 on 2024-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=True, verbose_name="featured"),
        ),
    ]
