# Generated by Django 4.2.4 on 2024-10-26 19:37

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0038_alter_product_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug_title",
            field=models.CharField(
                default="book", max_length=255, verbose_name="Slugged Title"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_keyword",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="SEO keywords"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Specifications"
            ),
        ),
    ]
