# Generated by Django 4.2.4 on 2024-10-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0039_product_slug_title_alter_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="author",
        ),
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.bookauthor",
                verbose_name="BookAuthor",
            ),
        ),
    ]
