# Generated by Django 4.2.4 on 2024-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0041_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_status",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")],
                default="True",
                max_length=40,
            ),
        ),
    ]
