# Generated by Django 4.2.4 on 2024-11-04 15:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0042_alter_comment_comment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytree",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="category/",
                validators=[products.models.validate_svg_file],
            ),
        ),
    ]
